### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by MattIPv4** [JetBrains/logos#2]
Android studio is now available in the toolbox application and so it would be very nice to have the logo for it added to this repo. Thanks :)

**Comment by kropp** [comment]
Despite the fact that Android Studio is not available in JetBrains Toolbox App, it's not a JetBrains product (we've explained this in the [blog post](https://blog.jetbrains.com/blog/2019/01/17/toolbox-app-1-13-with-android-studio/)). This repository is exclusive for JetBrains' products logos and to avoid confusion we are not going to add Android Studio logo here.
